name: Java CI

on: [push, pull_request]

jobs:
  build:
    name: build and test on Java ${{ matrix.Java }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '8', '11', '17' ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn -Dmaven.buildNumber.revisionOnScmFailure=no-scm test package
